### ISSUE TITLE
Codelite-terminal not working on MacOS 11.2

### ISSUE THREAD

**Issue by sanr7007** [eranif/codelite#2682]
Whenever I run a program, the program exits without the code-lite terminal opening and no errors are shown. However, the program runs successfully when I use Mac terminal. I am using Codelite 15.0 (the latest version)

**Comment by shvipin** [comment]
I am also seeing the same issue.
Terminal and iTerm are working fine but they are annoying to work with as window remains open after hitting enter when execution is finished.

```
Working directory is set to: /Users/vipin/codelite/build-Debug/lib
Executing: open /Users/vipin/Applications/codelite.app/Contents/MacOS/codelite-terminal.app --args  --working-directory=/Users/vipin/codelite/build-Debug/lib --file=/tmp/CodeLite.vipin_sharma.1615650997/codelite-terminal.txt --wait 
Program exited
```

Files in codelite-terminal.app
```
tree /Users/vipin/Applications/codelite.app/Contents/MacOS/codelite-terminal.app/
\-- Contents
    +-- Info.plist
    +-- MacOS
    │   +-- codelite-terminal
    │   +-- liblibcodelite.dylib
    │   +-- libplugin.dylib
    │   +-- libwx_osx_cocoau-3.1.4.0.0.dylib
    │   +-- libwx_osx_cocoau-3.1.4.dylib -> libwx_osx_cocoau-3.1.4.0.0.dylib
    │   +-- libwx_osx_cocoau-3.1.dylib -> libwx_osx_cocoau-3.1.4.dylib
    │   \-- libwxsqlite3.dylib
    \-- Resources
        \-- icon.icns
```

I tried running the "Executing" command by appending "Contents/MacOS/codelite-terminal" after codelite-terminal.app, that opens codelite terminal but I don't see the output from my code.

**Comment by Goosebumpzzz** [comment]
Having the same issue using v15.0.0 with OS 11.2.3

**Comment by MC722** [comment]
Having the same issue with MacOS Big Sur

**Comment by TRTurn** [comment]
I am having this issue on BigSur 11.4. My MacBook does have an M1 chip in case that is relevant.

**Comment by Velocity2021** [comment]
I have the same issue too

**Comment by eranif** [comment]
This issue should be fixed in the current master (and also in `15.0.5`) which version are you using?

**Comment by Velocity2021** [comment]
CodeLite 15.0.5 - Weekly Build July 6, 2021

**Comment by eranif** [comment]
Can you try and run it manually (without the `open` command), something similar to:

```
/path/to/codelite.app/Contents/MacOS/codelite-terminal.app/Contents/MacOS/codelite-terminal
```

Does this work for you? if not, what error do you get?

**Comment by Velocity2021** [comment]
zsh: no such file or directory: /path/to/codelite.app/Contents/MacOS/codelite-terminal.app/Contents/MacOS/codelite-terminal

**Comment by eranif** [comment]
Replace `/path/to/` with the **actual path** to `codelite.app` folder :)

**Comment by Velocity2021** [comment]
I think it was like this: 
zsh: permission denied: /Applications/codelite.app/Contents/MacOS/codelite-terminal.app

**Comment by eranif** [comment]
can you try and give it an executable permissions?

chmod +x /path/to/.../codelite-terminal

**Comment by Velocity2021** [comment]
I tried it. 

chmod +x/Applications/codelite.app/Contents/MacOS/codelite-terminal.app
usage:	chmod [-fhv] [-R [-H | -L | -P]] [-a | +a | =a  [i][# [ n]]] mode|entry file ...
	chmod [-fhv] [-R [-H | -L | -P]] [-E | -C | -N | -i | -I] file ...

**Comment by eranif** [comment]
you are missing a space.... after the +x

**Comment by eranif** [comment]
You are missing a space after the `+x`:

```bash
chmod +x /Applications/codelite.app/Contents/MacOS/codelite-terminal.app/Contents/MacOS/codelite-terminal
```
Once you did that, try to run it again like this (from a Terminal):

```bash
/Applications/codelite.app/Contents/MacOS/codelite-terminal.app/Contents/MacOS/codelite-terminal
```

**Comment by Gubbify** [comment]
> You are missing a space after the `+x`:
> 
> ```shell
> chmod +x /Applications/codelite.app/Contents/MacOS/codelite-terminal.app/Contents/MacOS/codelite-terminal
> ```
> 
> Once you did that, try to run it again like this (from a Terminal):
> 
> ```shell
> /Applications/codelite.app/Contents/MacOS/codelite-terminal.app/Contents/MacOS/codelite-terminal
> ```

I was having the same issue and after following all the steps and preforming the command I was able to open the codelite terminal but still not able to open the actual application through finder or spotlight search and on activity monitor it shows as not responding

**Comment by jdshaffer** [comment]
Same problem here... changing the permissions allows me to open the codelite-terminal.app directly, but it still will not open when I build and run a project in codelite, itself. (I, too, am running the latest Big Sur on an M1 chip).

**Comment by benjaminLightning** [comment]
Same issue as above. While tried to run the codelite-terminal directly from mac terminal:

/Applications/codelite.app/Contents/MacOS/codelite-terminal.app/Contents/MacOS/codelite-terminal
2022-03-12 04:30:35.524 codelite-terminal[6247:4157397] Warning: Expected min height of view: (<NSPopoverTouchBarItemButton: 0x7fa05030e8f0>) to be less than or equal to 30 but got a height of 32.000000. This error will be logged once per view in violation.
2022-03-12 04:30:35.525 codelite-terminal[6247:4157397] Warning: Expected min height of view: (<NSButton: 0x7fa050034c60>) to be less than or equal to 30 but got a height of 32.000000. This error will be logged once per view in violation.
2022-03-12 04:30:35.527 codelite-terminal[6247:4157397] Warning: Expected min height of view: (<NSPopoverTouchBarItemButton: 0x7fa05004c2c0>) to be less than or equal to 30 but got a height of 32.000000. This error will be logged once per view in violation.
2022-03-12 04:30:35.529 codelite-terminal[6247:4157397] Warning: Expected min height of view: (<NSPopoverTouchBarItemButton: 0x7fa050053360>) to be less than or equal to 30 but got a height of 32.000000. This error will be logged once per view in violation.


With this:
% /Applications/codelite.app/Contents/MacOS/codelite-terminal.app
zsh: permission denied: /Applications/codelite.app/Contents/MacOS/codelite-terminal.app
even after I grant it executable permission with

 chmod +x /Applications/codelite.app/Contents/MacOS/codelite-terminal.app

**Comment by bibhubal** [comment]
Is this issue is fixed. I don't know what to do but getting same issues. codelite-terminal is not opening while running the program in codelite.

**Comment by eranif** [comment]
switch to native terminal: preferences -> terminal

**Comment by Tyler-Pritchard** [comment]
I think I'm having a similar issue.  MacOS Monterey v12.3, CodeLite 15.0.10.  My program compiles, runs fine in Term & iTerm, but when I set the CodeLite terminal as the default terminal I get nothing.  I was able to run the application from the CodeLite terminal after using iTerm to launch the CodeLite terminal (using the cli commands noted upthread).

**Comment by timbarnes** [comment]
Same issue with CodeLite 16.1.0 on Mac Monterey 12.4. I can open the terminal from a shell, but it does not open when I run a program using the console from within CodeLite.

**Comment by sophiasp** [comment]
Same issue with CodeLite 16.0.0 on Mac Monterey 12.6, M1 Max. Tried switching from Terminal to codelite-terminal in Preferences > Terminal, but still doesn't work.
