### ISSUE TITLE
Highlight caret line is missing alpha/opacity value

### ISSUE THREAD

**Issue by uffejakobsen** [eranif/codelite#646]
Highlight caret line is missing alpha/opacity value

I'm using codelite with dark background color - and have set caret line highlight to bright yellow.
The result is nowhere near bright yellow - it looks more like a very dark green - diffucult to spot from the background.

PS: I believe (seem to remember) that the caret line highlight once had an aplha/opacity value ???

Seen with codelite 6.1 and 7.0 on ArchLinux

**Comment by eranif** [comment]
You are correct, I can't remember why it was removed (by me), I believe it was part of a page reorganization...
I will fix this today - thanks for spotting this
PS
There seems to be hard coded alpha: `SetCaretLineBackAlpha(30)`
also, using WHITE as the caret line gives a nice background over the black theme

![1](https://cloud.githubusercontent.com/assets/3677711/6123125/f4aadfa6-b106-11e4-9fd7-aef433899a22.png)

**Comment by eranif** [comment]
Fixed. (See screenshot below)
![editor-settings-7 1](https://cloud.githubusercontent.com/assets/3677711/6129984/da11366a-b14a-11e4-907b-df90758a6d39.png)

**Comment by uffejakobsen** [comment]
That was quick - thanks :+1:   :-)

**Comment by eranif** [comment]
I spent most of the time updating the UI, the real fix took 3 minutes :D
Would appreciate if you could test this to see that it works for you

**Comment by uffejakobsen** [comment]
It works much better now.
There seems to be some constant factor still present - because I still cannot get a full (bright) white or yellow highligh on a dark background - no matter what I adjust. I may have missed some point here.

**Comment by eranif** [comment]
You did not miss anything. Its just how it works. You can set it to 256 which disables the alpha completely. 

http://www.scintilla.org/ScintillaDoc.html#alpha

You can't make it full white or yellow on dark background, this is because the text is usually white or light gray - so the text will be invisible

**Comment by uffejakobsen** [comment]
Oh - I was focused on the value as a percentage and was only testing values from 1 to 100 - did not notice that it could go higher - my bad - sorry for the noise.

It is a really good solution - thanks

PS: not really sure what happens - but 256 is a much better value than 255 - and it does not seem to have wrapped - as 0 and 1 yeilds other results :-)

**Comment by eranif** [comment]
256 means: disable alpha completely
0-255 means: 0 is complete transparent, 255 fully opaque

**Comment by uffejakobsen** [comment]
Aaaah thx - it is clearly written in the docs - I guess that I'm too busy multiplexing between $work and this stuff - apologies for the noise :-)
